name: Auto Update Gbox Formula

on:
  schedule:
    # Run every hour to check for new releases
    - cron: "0 * * * *"
  workflow_dispatch:
    # Allow manual trigger
    inputs:
      version:
        description: "Gbox version to update to (optional, will auto-detect latest if not specified)"
        required: false
        type: string

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install required tools
        run: |
          # Install GitHub CLI
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install curl wget jq gh -y

      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Gbox formula
        run: |
          # Use the update script (it will auto-detect version and check if update is needed)
          if [ -n "${{ github.event.inputs.version }}" ]; then
            bin/update-gbox.sh -v "${{ github.event.inputs.version }}"
          else
            bin/update-gbox.sh
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        run: |
          # Use the PR creation script
          bin/create-pr.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
